### PR TITLE
Initial OpenTimelineIO Specification

### PR DESCRIPTION
**Pull request by reinecke**
This pull request adds a specification for the OpenTimelineIO data model along with validation tools.

These provide:
- HTML generation of the data model documentation (example [here](https://sandflow.github.io/otio-core-specification/))
- Generation of [JSON Schema](https://json-schema.org/) to validate .otio JSON files (example [here](https://sandflow.github.io/otio-core-specification/otio.schema.json))

This specification was developed by @palemieux on behalf of Netflix for the OpenTimelineIO project.

Co-authored by: @palemieux

### CODE REVIEW

**Comment by meshula** [comment]
What would be a good way to link this to the Documentation project in the main repo? Pierre's original PR is there.

**Comment by reinecke** [comment]
Perhaps we should close that PR (https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/819) with a link to this one?
I'll happily take care of that if we agree that's the way forward.

I think the next step is to add a github action in this repo to publish build products, then we can discuss how we want to make the main repo reference this one. It would be nice to see if we can avoid the git submodule approach.

**Comment by meshula** [comment]
Ok, I'll vote YES for closing the original PR in favor of this.

**Comment by reinecke** [comment]
Per 1/6/2022 OTIO Meeting, merging this PR.

**Pull request merged**
